### ISSUE TITLE
Docker Playground With LLaMA And PyLLaMA

### ISSUE THREAD

**Issue by soulteary** [juncongmoo/pyllama#13]
Hi @juncongmoo 

I made a simple Docker image to run LLaMA and your PyLLaMA.

Hope that helps

https://github.com/soulteary/llama-docker-playground

> Life time is precious, and there is no need to toss about the installation environment

**Comment by juncongmoo** [comment]
Thank you @soulteary . Feel free to submit a PR by adding a section in README
