### ISSUE TITLE
Download takes forever

### ISSUE THREAD

**Issue by puyuanliu** [juncongmoo/pyllama#29]
Stuck at "downloading file to llama_7B/7B/consolidated.00.pth" for several hours.  I checked the size of the model folder, it's around 6.6GB. The size stays constant. 

The following are script outputs.

❤️ Resume download is supported. You can ctrl-c and rerun the program to resume the downloading
Downloading tokenizer...
✅ llama_7B/tokenizer.model
✅ llama_7B/tokenizer_checklist.chk
tokenizer.model: OK
Downloading 7B
downloading file to llama_7B/7B/consolidated.00.pth ...please wait for a few minutes ...

**Comment by cccadet** [comment]
"Ctrl + C" to cancel and try again.

**Comment by puyuanliu** [comment]
Worked! Thanks a lot!
