### ISSUE TITLE
No module named "transformers" error

### ISSUE THREAD

**Issue by SimoGiuffrida** [juncongmoo/pyllama#33]
When i try to run "python -m llama.download --model_size 7B", it says that python command doesnt exist, so i have to use "python3" command, but once i write "python3 -m llama.download --model_size 7B", all these errors appears
![image](https://user-images.githubusercontent.com/93772564/225869743-aabc7b1f-a953-4860-960b-5eb81fa0b1b5.png)
Can someone help me figure out what is wrong?

**Comment by Bradley-Butcher** [comment]
`pip install transformers` - dev needs to add it to req
