### ISSUE TITLE
Tips: hiq_python support py3.8+

### ISSUE THREAD

**Issue by SWHL** [juncongmoo/pyllama#7]
HiQ supports Python version 3.8 and higher. Your version is 3.7.

**Comment by vmajor** [comment]
I am using `python 3.10.9` and `hiq` is installed:

`hiq                0.0.1`

but I get this:

```
model_single.py", line 8, in <module>
    import hiq
ModuleNotFoundError: No module named 'hiq'
```

What do I do?
