### ISSUE TITLE
downloading file to pyllama_data/30B/consolidated.00.pth ...please wait for a few minutes ...

### ISSUE THREAD

**Issue by Nolyzlel** [juncongmoo/pyllama#88]
Downloading since 60 minutes. No ending in sight with message seen in title. I work with a high performance Google VM. Seems to me that this cant be the issue.

**Comment by zhangbonian** [comment]
comment out line 86: "download_watchdog(args)" in download.py, on my machine, md5sum takes more than 30s to finish, the watchdog thread think progress is too slow , so restarted the download process. In fact the download was already finished.

**Comment by Jack-Moo** [comment]
I will send a PR.
