### ISSUE TITLE
Why are params.json empty?

### ISSUE THREAD

**Issue by ItsCRC** [juncongmoo/pyllama#93]
I have downloaded both 7B & 13B. Both have params.json empty in their respective folders. I need to convert weights into hugging_face format and need params.json for that.

**Comment by sunggukcha** [comment]
![image](https://github.com/juncongmoo/pyllama/assets/31852410/f541592f-5def-496d-936f-ea2f2ed6a6ed)
For me, all files are empty (0 bytes) and the downloading is conducted in a second.

**Comment by ItsCRC** [comment]
Same happened for me. For me, the issue was that there was no storage left in my device. The script did not notified me of that and instead showed all downloaded. Upon freeing the space, I got correct files.

**Comment by sunggukcha** [comment]
> ![image](https://user-images.githubusercontent.com/31852410/241123765-f541592f-5def-496d-936f-ea2f2ed6a6ed.png) For me, all files are empty (0 bytes) and the downloading is conducted in a second.

For me, it might be the certificate issue.
Eventually I downloaded with different script (https://github.com/shawwn/llama-dl) with `--no-check-certificate` options to all wget commands.

**Comment by ItsCRC** [comment]
Did it work?

**Comment by sunggukcha** [comment]
Is working. 
Though I havent looked into the script of this repo, I am thinking the error I faced was the certificate issue.
